baseURL = "https://opengood.io/"
languageCode = "en-us"
title = "OpenGood.io"
theme = "hyde-hyde"

[params]
  author = "OpenGood.io"
  description = "OpenGood.io"
  authorimage = "/images/opengood-io.png"
  dateformat = "Jan 2, 2006"
  highlightjs = true

[params.social]
    github = "opengood-io"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
